---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
    driver:
      customize:
        memory: 1024
  - name: ubuntu-12.04
    driver:
      customize:
        memory: 1024

suites:
  - name: default
    run_list:
      - recipe[dhcp-dash::default]
    attributes:
